import 'package:flutter/material.dart';
import 'screens/profile_selection.dart';
import 'screens/home.dart';
import 'screens/record.dart';
import 'screens/timeline.dart';
import 'screens/archive.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'models/profile.dart'; // Make sure this imports the generated adapter as well

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();

  // Register the Profile adapter (generated by build_runner)
  Hive.registerAdapter(ProfileAdapter());
  runApp(SmritiApp());
}

class SmritiApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smriti',
      theme: ThemeData(primarySwatch: Colors.indigo),
      initialRoute: '/',
      routes: {
        '/': (context) => ProfileSelectionPage(),
        '/home': (context) => HomePage(),
        '/record': (context) => RecordPage(),
        '/timeline': (context) => TimelinePage(),
        '/archive': (context) => ArchivePage(),
      },
    );
  }
}
